### ISSUE TITLE
Всплывающее сообщение в шторке (в уведомлении)

### ISSUE THREAD

**Issue by OmlineEditor** [impalex/knockonports#15]
В момент стука появляется всплывающее сообщение в шторке (в уведомлении) о том что мы стучим в ... Есть там кто-то? Это сообщение не меняется даже после того как постучали и его нельзя закрыть раньше времени т.к. запущена служба.

Прошу сделать следующее:
1) После стука менять сообщение на текст "Мы уже постучали в ..."
2) Разрешите закрывать сообщение в шторке (в уведомлении) досрочно, а не автоматом через минуту после стука. т.е. разрешите останавливать службу раньше времени, например при клике по сообщению.

**Comment by impalex** [comment]
п 1. Зачем?
п 2. Что значит "через минуту"? Уведомление висит ровно то время, которое необходимо для того, чтобы отправить полную последовательность. Кончилась отправка - уведомление убрано, все.

**Comment by OmlineEditor** [comment]
1) Это же по логике вещей, если написано стучим значит процесс сейчас происходит и не закончен, а когда написано что уже постучали значит процесс стука закончился и можно делать что-то дальше.
2) у меня висит после стука еще 1 минуту примерно и служба запущенна еще после стука и не закрывается сразу автоматом после стука.

**Comment by impalex** [comment]
Уведомлеие не должно оставаться после завершения последовательности. Если остается - какой-то баг. Впервые слышу о таком поведении.
Какое устройство? Версия андроида? Оригинальный андроид или модифицированный? Если не оригинальный - кто вендор или как называется сборка? Есть ли возвожность предоставить logcat?

**Comment by impalex** [comment]
Дополнительные вопросы:
1. В логе приложения - корректно ли определяется внешний ip?
2. В логе приложения - время (обращая особое внимание на секунды) - совпадает с "исчезновением" уведомления? Или записывается до исчезновения?

**Comment by OmlineEditor** [comment]
1) в логах я вижу: IP куда нужно стучать (свой IP → IP куда стучать) Мой IP показывается верно
2) В логах время показывается на момент нажатия на кнопку "постучать" с точностью до секунды и запись в логах появляется в момент исчезновения уведомления, а это примено через 40 сек после нажатия на кнопку стучать.

Много раз тестирую и проверяя, я заметила что иногда надпись в шторке исчезает сразу а иногда с задержкой в примерно в 40 сек. Есть подозрение что ваша программа висит в памяти еще 40 сек чтобы получить мой белый IP и если она не может получить его просто ждет 40 сек и отваливается по таймауту. Возможно проблема не у вас а в сервисе icanhazip.com откуда вы получаете IP. Знаний у меня не достаточно чтобы точно сказать где именно проблема, если нужно что-то еще для помощи скажите, я попробую это сделать.

**Comment by impalex** [comment]
Исходя из описания, можно сделать вывод, что проблемы с определением внешнего IP. Возможно, какие-то проблемы со связью.
Могу разве что предложить возможность выбирать сервис, через который будет определяться адрес и/или отключать эту функцию.

**Comment by OmlineEditor** [comment]
Хорошая идея, добавьте в настройки вариант: сервер для определения внешнего IP и туда можно было бы вбивать строку типа: http://icanhazip.com или две, три строки чтобы задать резервный адрес или выключать эту функцию совсем.

Я щас проверила как у меня открывается сайт http://icanhazip.com, и он иногда просто не открывается. Проблема похоже реально в нем, а ваша программа работает как нужно. 

Как добавите в настройки эту функцию закрывайте тикет. Спасибо за поддержку.

**Comment by impalex** [comment]
Отключение, выбор, задание своего сервиса доступно в 1.1.6
