### ISSUE TITLE
[Enhancement] - Add IPv6 support

### ISSUE THREAD

**Issue by RastaTaz** [impalex/knockonports#16]
It would be nice if could add IPv6 support !

**Comment by impalex** [comment]
Work in progress. IPv6 support will be available in the next release.

**Comment by RastaTaz** [comment]
Hi impalex,

Glad to hear that : thanks !

If I may allow myself a suggestion on the implementation : as said in #9, a IPv4/IPv6 switch in the knock sequence config would be nice, but a "both" option would be even better !
Indeed : as I don't know which one I will use (it depends on the app I would use after the knock I guess), I rather allow both IPv4 and IPv6 to go through my firewall at once with a single knock ;o)

**Comment by impalex** [comment]
Yes, there will be different modes available. Including suggested by you. 
Unfortunately, I cannot say exactly when.
If you wish, you can join the testing track. All new features will be available in the alpha track before going live.

**Comment by RastaTaz** [comment]
Sure, I'll be glad to contribute by joining "testing track".

How is that done ? Enabling "unstable" applications in the store ?

**Comment by impalex** [comment]
Send your email to dev@impa.me, I will add you to the list and send you an invitation to join.

**Comment by impalex** [comment]
Done. Version 1.1.6.
