### ISSUE TITLE
[Enhancement] - Add timer to repeat knock

### ISSUE THREAD

**Issue by RastaTaz** [impalex/knockonports#17]
I know you added tasker integration, but the latter is not free...
It would be nice to add a timer to repeat knock sequence

Usage example : be sure to open access again via port knocking from my mobile phone on:
- knock timeout (on my firewall)
- mobile phone ip change
=> a simple timer to repeat knock sequence should do the trick

**Comment by impalex** [comment]
If you don't want to use Tasker, use MacroDroid, it's free.
No, I will not add automation to the port knocking tool. If you want to automate knocking, use third party tools, it's more versatile.

**Comment by RastaTaz** [comment]
ok : thanks for advice !
