### ISSUE TITLE
Добавить новый способ стука - Вебхук (Webhooks)

### ISSUE THREAD

**Issue by OmlineEditor** [impalex/knockonports#21]
Если по простому то Вебхук - это HTTP-запрос на определенный URL-адрес.
Например так открываем ссылку и на сервере начинают работать определенные механизмы:
https://myServer.com/secretFolder/script.php?cmd=openPort22

**Comment by impalex** [comment]
Зачем для этого приложение? Это просто ссылка, достаточно браузера и закладки.

**Comment by OmlineEditor** [comment]
Просто привычки использовать для стука вашу программу. А браузер это немного не то, хотя и можно выполнить эту задачу через него.
Сможете добавить Webhooks в свою программу?

**Comment by impalex** [comment]
Есть три вида нокинга:
1. Использование TCP-портов - поддерживается.
2. Использование ICMP-пакетов - поддерживается.
3. Использование SPA-пакетов - не поддерживается.

Всё. Использование http-запросов для целей приложения - это что-то самоизобретенное. В приложении лишнее, не вижу смысла добавлять такое.
К тому же, повторюсь, для этих целей приложение не нужно.

Ярлык с этим запросом можно положить на домашний экран штатными средствами андроида. Всё, одно нажатие на ярлык - запрос выполнен.

Если не знаете, как это делается, то можно почитать, к примеру, здесь - https://www.howtogeek.com/196087/how-to-add-websites-to-the-home-screen-on-any-smartphone-or-tablet/

**Comment by OmlineEditor** [comment]
![Okay_meme](https://user-images.githubusercontent.com/13348933/155597644-1f58368a-66cf-4edc-9a45-9d3d91809c17.png)
