### ISSUE TITLE
UI Feature Request: Prompt for deletion

### ISSUE THREAD

**Issue by iointerrupt** [impalex/knockonports#3]
Just a small request to have a prompt for delete or perhaps as a prompt on long press instead of a straightforward easy to press delete icon.  Possible to accidentally deleting an entry is too easy.  Great app btw.

**Comment by impalex** [comment]
Good suggestion, thank you. Noted.

**Comment by impalex** [comment]
Okay... Operation has been hidden in the context menu. You need at least two taps to remove an entry. I think this solves the issue.
![image](https://user-images.githubusercontent.com/13515747/51162991-106be180-18ba-11e9-935e-8132cfa3457b.png)
