### ISSUE TITLE
NDK version to use?

### ISSUE THREAD

**Issue by relan** [impalex/knockonports#4]
Hi,

F-Droid uses NDK r12b by default which is probably not the right one. Which NDK should we use?

**Comment by impalex** [comment]
I saw the error. Already rolled back the native code that caused it, now it should compile just fine.

**Comment by impalex** [comment]
As for the framework... The latest version r19c is used to build for Google Play. But r12c should be fine.

**Comment by relan** [comment]
> But r12c should be fine.

Well, it's not:
```
app/src/main/cpp/netutil.cpp:108:46: error: use of undeclared identifier 'SOCK_NONBLOCK'
      int sock = socket(PF_INET, SOCK_STREAM | SOCK_NONBLOCK, 0); // NOLINT(android-cloexec-socket,hicpp-signed-bitwise)
                                               ^
```

I set NDK to r19. Now it compiles.

**Comment by impalex** [comment]
Ah. Right.
Did you fixed it in metadata?

**Comment by relan** [comment]
Yes, in this commit: https://gitlab.com/fdroid/fdroiddata/commit/378729b2d12fbb82984d276ecd55ce52b6ff0a9c

**Comment by impalex** [comment]
Thank you.
