### ISSUE TITLE
"Network unreachable" not works

### ISSUE THREAD

**Issue by tieugene** [impalex/knockonports#6]
It say "Knocking ok" when device has no Internet connection.

**Comment by impalex** [comment]
Ok, let's discuss.

First of all, an Internet connection is not required; the remote host can be on the local network.

So, we need to check somehow if the remote host is available, right? How? The remote host doesn't need to answer to our packets. It doesn't matter which packets we use - UDP, TCP or ICMP. In fact, on a properly configured server, each packet sent looks like a lost one.

All I can do is check if **any** network available, that's all. If the network is available, I see no way to **accurately** verify the availability of the host.

Any thoughts?

**Comment by impalex** [comment]
BTW, you can use the host name instead of its ip. In this case the knock will fail if there is no network.

**Comment by tieugene** [comment]
1. Replace "Internet connection" with "wifi connection" - it is not matter.
We need to check did IP packets have sense.
Next - did remote host received our TCP packets (as minimum). I'm not sure about UDP or ICMP.
Yes - checking _any_ IP network availability is necessary condition.
Verifying host is not available in some conditions (e.g. strict firewall rules), but TCP packets must be delivered with right response.
And next - my device not resolved host by hostname in this application.
I'll try more.

**Comment by impalex** [comment]
As I said, there is no way to detect if a packet was delivered or not, even for TCP.
We can say this for sure if the server accepts or rejects our connection. But it can just drop the packet, this is a valid case. And in this case, we do not know whether this packet was delivered or not.

**Comment by impalex** [comment]
I will add a check if any network is available... But I'm afraid that checking packet delivery is not possible.

**Comment by impalex** [comment]
Network connectivity check added in version 1.1.3
Unfortunately, as I said before, there is no way to check if the packet was delivered or not. Even for TCP.
