### ISSUE TITLE
Добавление логов о стуке

### ISSUE THREAD

**Issue by OmlineEditor** [impalex/knockonports#7]
Можно добавить ведение логов? т.е. в какое время и с какого IP стучали. 
Для повышения безопасности потом можно будет проверять время и IP с логами сервера куда стучали.

Если возможно добавьте логи для повышения информативности и безопастности.
Пример логов (Дата Время (IP) Название Хоста):
- 10 фев. 2020 15:31 (IP: 10.20.30.40) Сервер Марины
- 11 фев. 2020 16:47 (IP: 11.22.33.44) Сервер на работе

**Comment by impalex** [comment]
Принято.

**Comment by OmlineEditor** [comment]
Для получения внешнего IP (не серого от правайдера IP) можно использовать простой сайт типа такого http://icanhazip.com он показывает только IP без лишних данных. Я обычно его использую, возможно есть еще похожие сайты которые показывают только IP, но я их не искала. Если найдете еще добавьте в программу несколько вариантов, буду зв это очень признательна.

**Comment by impalex** [comment]
Добавлено в 1.1.5, обновление доступно в маркете.
Спасибо.
