### ISSUE TITLE
Добавить размер пакетов для TCP

### ISSUE THREAD

**Issue by OmlineEditor** [impalex/knockonports#8]
Можно ли добавить возможность сказать какие данные отправить или просто указать размер данных для пакета TCP.  Сейчас есть возможность сказать данные для UDP и указать размер пакета для ICMP, а для TCP нет такой возможности.
После всех основных заголовков есть возможность сказать, что за данные отправляются:
https://ru.wikipedia.org/wiki/Transmission_Control_Protocol

У меня есть возможность использовать только 80 и 443 порты т.к. открыт доступ в интернет только для сайтов. Хотелось бы иметь возможность стучать размерами пакетов в эти порты. На одном из них сидит кстати OpenVPN, так что по хорошему, лучше использовать только 80й порт и стучать в него.

**Comment by impalex** [comment]
Это невозможно из-за ограничений протокола, ссылку на его описание Вы привели.
Для "стука" используются пакеты с флагом SYN - см. раздел "Механизм действия протокола".
Управлять содержимым SYN-пакетов нет никакой возможности, как, если честно, и потребности, мне неизвестно  ни одной реализации нокинга, где от TCP требовались какие-то определенные размеры или содержимое.
